### ISSUE TITLE
Problems on the ios

### ISSUE THREAD

**Issue by renanzdm** [ekasetiawans/flutter_bluetooth_printer_plugin#1]
First of all thank you very much for the package which is very good.
I'll explain how I'm using your plugin to print.
For greater customization I'm generating the HTML prints
and I'm converting them to image using this package https://pub.dev/packages/webcontent_converter but since it's not null-safety I forked it and I'm using it straight from my github
https://github.com/renanzdm/webcontent_convert_forked I intend to upload it if the author does not update it.
  - On android it works perfectly when sending the entire byte list, but on IOS there is a limitation that when the list is too much
  great impression does not occur, the way I found it was to divide this list and send it in parts.
```dart 
 final len = data.length;
 List<List<int>> chunks = [];
 for (var i = 0; i < len; i += 100) {
   var end = (i + 100 < len) ? i + 100 : len;
   chunks.add(data.sublist(i, end));
 }
 for (var i = 0; i < chunks.length; i++) {
 device.printBytes(bytes:Uint8List.fromList(chunks[i]));
 }
```
Doing this seems to work fine on ios, and on android you need to do a check to then send the list in its normal size
as I don't know the Objective-C language, it can't implement directly in native (which I think would be ideal)

  - On the native android I made some changes in terms of asking for location permission when scanning, and it worked well
  I would like your opinion and if possible a response to these changes
  Appreciate

**Comment by ekasetiawans** [comment]
you can call `printImage` method to print an image. The image provided is just raster type of your full receipt. Make sure you have resize the image depending to the paper size you use.
