### ISSUE TITLE
convert pdf to images 

### ISSUE THREAD

**Issue by maxzod** [ekasetiawans/flutter_bluetooth_printer_plugin#11]
works fine on `2.3.0` ✔
after upgrade to `flutter_bluetooth_printer: ^2.6.3`
the api for `FlutterBluetoothPrinter.printImage` changed 
no i have to pass a `List<int>` instead of image from package `image`

i tried to use `image.getBytes()`

the code i use to convert pdf to image
```dart
Future<Image> convertPdfUnit8ListToImage(
  Uint8List docBytes, [
  double? width,
]) async {
  final watch = Stopwatch()..start();
  final document = await x.PdfDocument.openData(docBytes);
  final page = await document.getPage(1);
  final image = await page.render(
    width: width ?? page.width * 3,
    height: page.height * 3,
    format: x.PdfPageImageFormat.png,
  );
  page.close();
  final img = decodeImage(image!.bytes.buffer.asUint8List());
  watch.stop();

  log('it took ${watch.elapsed.inSeconds} Seconds');
  if (img != null) return img;
  throw Exception('Could not decode image');
}

```
but the package print a dark image  blow i will 
before update :
![صورة واتساب بتاريخ 2022-12-18 في 16 46 35 (2)](https://user-images.githubusercontent.com/47630729/208304840-c5afb8d2-63b9-4b27-8cd4-2dc6c4bef1ed.jpg)
after update and use bytes 
![صورة واتساب بتاريخ 2022-12-18 في 16 46 35](https://user-images.githubusercontent.com/47630729/208304868-21ba2ac5-4b61-40e9-af4a-a0f6143bbfbd.jpg)

**Comment by ekasetiawans** [comment]
the List<int> image is raw ARGB bytes, i recommends to use Receipt widget instead
