### ISSUE TITLE
2.6.3 I cannot discovery bluethooth device in IOS. Please help

### ISSUE THREAD

**Issue by kuanh1410** [ekasetiawans/flutter_bluetooth_printer_plugin#12]
I updated version from 2.3.0 to 2.6.3 then I cannot discovery bluethooth device :( 
In android, everything ok but IOS...And version 2.3.0 - android i print Receipt from widget Receipt it is fast and IOS is so slow :( Please help !!!!

**Comment by ekasetiawans** [comment]
please retry with 2.7.1 that i've published recently
on android, we use raw socket that much faster, unfortunately on ios we must use BLE that its very limited in payload size, so it slower.

**Comment by kuanh1410** [comment]
Hopefully there will be a faster way to print on iOS. If possible. Please include the version change log so we can all know. Thank you so much

**Comment by ekasetiawans** [comment]
> Hopefully there will be a faster way to print on iOS. If possible. Please include the version change log so we can all know. Thank you so much

Unfortunately, currently Apple only provide BLE communication to us for general (cheap) bluetooth printer devices.
