### ISSUE TITLE
Layout issue when i print second time

### ISSUE THREAD

**Issue by huzaifasaeed** [ekasetiawans/flutter_bluetooth_printer_plugin#13]
When start my printer and start printing first time it is working good.
https://user-images.githubusercontent.com/12073650/209156197-f1fb3299-f534-4b15-8b1b-7974f35e634e.jpeg

But when i print second time its show layout like this. 
https://user-images.githubusercontent.com/12073650/209156569-154df2d5-8667-46d4-af0e-d2a5e88e04ea.jpeg

If any one have idea please share.

**Comment by huzaifasaeed** [comment]
Yes its fully printed.

**Comment by huzaifasaeed** [comment]
@ekasetiawans Fixed, its our printer issue thanks man.

**Comment by mhmdelngar** [comment]
How you fixed your printer please @huzaifasaeed
