### ISSUE TITLE
Image Optimization

### ISSUE THREAD

**Issue by seel-channel** [ekasetiawans/flutter_bluetooth_printer_plugin#2]
### Your package has no problem. It works fine!

I generated receipts using widget but my printers (I tested on 2 diferent printers) took to much to print the image. They are using the same time to print a receipt against black receipt. When I printed a default text, it works fine.

### My solution (I don't know how implement it): 
Using `img.Image` object we can create boxes with content a remove blank spaces. The big problem, ECS Printers can't print using coordinates. For example, print image with start at Offset(5, 10).

### Receipt
https://user-images.githubusercontent.com/65832922/140588560-04378964-b8d3-4dd0-8b35-698e52303cab.mp4

### Black receipt
https://user-images.githubusercontent.com/65832922/140588558-ac677e4c-c014-4f06-beaa-717ed489875d.mp4

**Comment by ekasetiawans** [comment]
@seel-channel hi, i'm sorry for not writing documentation yet. I build and use this plugin to print receipt that built with pdf package and printing plugin. So, you can build your own receipt with it and make sure you have correct paperSize.
