### ISSUE TITLE
No meaningful example 

### ISSUE THREAD

**Issue by mensur-durakovic** [ekasetiawans/flutter_bluetooth_printer_plugin#3]
Can someone provide good example for this plugin and how to print test page? And some documentation what exactly this plugin offers?

I am trying to find something that fits both Android and iOS

CC @ekasetiawans

**Comment by ferns-it** [comment]
https://github.com/ferns-it/test_printer.git

**Comment by ekasetiawans** [comment]
@mensur-durakovic clone this repository to your local dev environment, you will find the example project in `flutter_bluetooth_printer_plugin/tree/master/packages/flutter_bluetooth_printer/example`
