### ISSUE TITLE
Unable to run project when combined with esc_pos_printer library, i need to use both wifi and bluetooth printer.

### ISSUE THREAD

**Issue by spoorknight** [ekasetiawans/flutter_bluetooth_printer_plugin#30]
<img width="1291" alt="Screenshot 2024-02-26 at 22 45 23" src="https://github.com/ekasetiawans/flutter_bluetooth_printer_plugin/assets/57425876/0b8d8d7f-047b-4c40-adcc-c14cf140a4a5">

**Comment by ekasetiawans** [comment]
try to update the latest version

**Comment by spoorknight** [comment]
> try to update the latest version

<img width="1382" alt="Screenshot 2024-02-26 at 22 50 58" src="https://github.com/ekasetiawans/flutter_bluetooth_printer_plugin/assets/57425876/49d14dc3-39b3-4769-b5db-eb2c5e3fc5a3">

i can't ....

**Comment by ekasetiawans** [comment]
i think esc_pos_printer has not updated since 2 years ago so it's obsolete try to change to esc_pos_printer_plus package

**Comment by spoorknight** [comment]
> i think esc_pos_printer has not updated since 2 years ago so it's obsolete try to change to esc_pos_printer_plus package

I just tried it and it fixed the old error, but there is a new problem

<img width="1330" alt="Screenshot 2024-02-26 at 23 03 40" src="https://github.com/ekasetiawans/flutter_bluetooth_printer_plugin/assets/57425876/971774bf-d8b7-4dcb-b0b4-32c4fb153064">
