### ISSUE TITLE
[Bug] Image prints with black image

### ISSUE THREAD

**Issue by minhtritc97** [ekasetiawans/flutter_bluetooth_printer_plugin#31]
I use FlutterBluetoothPrinter.printImage and get black image

![IMAGE 2024-02-27 14:06:13](https://github.com/ekasetiawans/flutter_bluetooth_printer_plugin/assets/48729090/b0b0afb8-3987-4de0-96c0-8a6975959628)

**Comment by parameshmamidisetti** [comment]
i too

**Comment by shahirsoft** [comment]
i too

**Comment by ekasetiawans** [comment]
hi @minhtritc97 sorry for delay, could you try the latest version?

**Comment by parameshmamidisetti** [comment]
yes, I have tried the new version. 
it's not working

**Comment by ekasetiawans** [comment]
> yes, I have tried the new version. it's not working

is it still black?

**Comment by minhtritc97** [comment]
it worked on version 2.13.0
thank for supporting
