### ISSUE TITLE
Papersize 80mm

### ISSUE THREAD

**Issue by u-sour** [ekasetiawans/flutter_bluetooth_printer_plugin#45]
hi @ekasetiawans, how can i change paper size from 58mm to 80mm ? thank in advance.

**Comment by haidang750** [comment]
interested.

**Comment by haidang750** [comment]
hi @u-sour , I want to ask you whether you can print on IOS platform? I worked well on Android but couldn't print on IOS version 17. Is there any required permission I have to add to Info.plist?

**Comment by ekasetiawans** [comment]
Currently I don’t owned the 80mm printer, but if you want to cotribute you can fork the repository and add the PaperSize enum. Make sure the paper width is the max dot per lines, you can find it from the printer device information or printer test page.

**Comment by u-sour** [comment]
@haidang750 i haven't tested it on IOS yet maybe tomorrow.  @ekasetiawans oh, i don't owed it, too. maybe i can borrow from friend to test it, can you show which line of code i need to add ?

**Comment by u-sour** [comment]
@haidang750 i just test it on IOS version 17.5.1 it works.

**Comment by haidang750** [comment]
@u-sour which printer did you use to test it?

**Comment by haidang750** [comment]
and can you please share your permissions about Bluetooth in your Info.plist file?

**Comment by u-sour** [comment]
> @u-sour which printer did you use to test it?

Printer: [MPT-II 58mm](https://www.aliexpress.com/item/1005005584978025.html)

**Comment by u-sour** [comment]
> and can you please share your Bluetooth permissions in your Info.plist file?

Info.plist : 
```
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Flutter Template</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleLocalizations</key>
	<array>
		<string>en</string>
		<string>km</string>
	</array>
	<key>CFBundleName</key>
	<string>flutter_template</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>Bluetooth permission is required for accessories connecting.</string>
	<key>NSCameraUsageDescription</key>
	<string>Camera permission is required for barcode scanning.</string>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>bluetooth-central</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</dict>
```

**Comment by haidang750** [comment]
thank you @u-sour

**Comment by u-sour** [comment]
> thank you @u-sour

nvm 😄

**Comment by haidang750** [comment]
hi @u-sour , have you found the solution for case paperSize 80mm?

**Comment by u-sour** [comment]
@haidang750 i don't have a mini printer 80mm to test it while i going to borrow it from my friend it broken.

**Comment by hiruworld** [comment]
Hello Guys,

Have you ever found a solution for this?

**Comment by u-sour** [comment]
@ekasetiawans Hi, I just got an 80mm printer. Can you show me which line and file I should change? Maybe I can help you test it.

**Comment by u-sour** [comment]
solved and tested it, it works.
**Printer Model:**
[MPI III 80 mm](https://www.flipkart.com/milestone-mpt-iii-cx80b-80mm-3-inch-thermal-printer-small-business/p/itmca2779a176806?pid=PTIGG36FSVWTNTCX&lid=LSTPTIGG36FSVWTNTCXQI7EA7&marketplace=FLIPKART&store=search.flipkart.com%2F6bo%2Ftia%2Fffn%2Fw07)
**Result:**
![2024-10-16 09 37 53](https://github.com/user-attachments/assets/441700e0-e1e6-4e12-ba85-44a4d99f0526)

**Comment by u-sour** [comment]
@ekasetiawans can merge this https://github.com/ekasetiawans/flutter_bluetooth_printer_plugin/pull/49 ?
anyone who wants to use 80mm option can use my repo:

Pubspec.yaml
```
  flutter_bluetooth_printer:
    git:
      url: https://github.com/u-sour/flutter_bluetooth_printer_plugin.git
      ref: add-80mm-option
      path: packages/flutter_bluetooth_printer
```

**Comment by ekasetiawans** [comment]
cool, i'll publish soon

**Comment by u-sour** [comment]
@ekasetiawans thank you, By the way, addFeeds doesn't work on paper size mm58 but mm80 it's ok. cloud you check it, please? 🤔  I will close this issue and reopen a new issue about it.
