### ISSUE TITLE
Supported Printers

### ISSUE THREAD

**Issue by jobypthomas** [ekasetiawans/flutter_bluetooth_printer_plugin#5]
What are the supported printers?
Does it work withe the printers supported by package [esc_pos_bluetooth](https://pub.dev/packages/esc_pos_bluetooth)?

**Comment by ekasetiawans** [comment]
@jobypthomas this plugin can be used with any bluetooth printer that support ESC Command.

**Comment by huzaifasaeed** [comment]
@ekasetiawans Thanks for this easy to use plugin :)
