### ISSUE TITLE
add line feed & disable scroll on receipt

### ISSUE THREAD

**Issue by YouSour** [ekasetiawans/flutter_bluetooth_printer_plugin#7]
hi, first of all i really like this package easy to use , i want to add line feed (space) when printer printed and is it possible or not if i want to disable scroll on receipt.  thank in advance

**Comment by ekasetiawans** [comment]
for Receipt widget, currently you can add an additional small period text at the bottom to add spaces. But, you can always send the bytes in ESC POS format to the printer if you implements your custom receipt widget. I'll consider to add parameters to the receipt widget print method in the future.

**Comment by YouSour** [comment]
@ekasetiawans  thank you for reply this tip, i 'll wait for this for next update, awesome package 👍

**Comment by ekasetiawans** [comment]
hi @YouSour I have updated the package, now you can use 

```dart
ReceiptController.print(
...
linesAfter: 2 // will print 2 feeds at the bottom
)
```

thank you

**Comment by YouSour** [comment]
@ekasetiawans thank you so much for keep update this awesome package and i hope you can improve document too, i will keep recommend everyone using this package, by the way on latest version how  can i set paper size ?

**Comment by ekasetiawans** [comment]
@YouSour you can change ReceiptController.paperSize, see the example project

**Comment by YouSour** [comment]
@ekasetiawans thank you , found it 😄
